include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    prefer_relative_imports: false
    avoid_types_on_closure_parameters: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    avoid_catches_without_on_clauses: false
    await_only_futures: true
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
